# Generated by Django 4.1.2 on 2022-10-28 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 14, 56, 26, 984161), verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 28, 14, 56, 26, 983150, tzinfo=datetime.timezone.utc)),
        ),
    ]
